### ISSUE TITLE
Dynamic Symbol Retrieval Error on Windows 10

### ISSUE THREAD

**Issue by Urik** [cjlarose/argon2-ffi#20] opened 2016-06-17 17:26 UTC
argon2-ffi is failing when running on Windows 10. I'm getting the following error:  

```
c:\Trabajo\Mesh01\wear-test-track0>node app.js
c:\Trabajo\Mesh01\wear-test-track0\node_modules\argon2-ffi\node_modules\ffi\lib\dynamic_library.js:112
    throw new Error('Dynamic Symbol Retrieval Error: ' + this.error())
    ^

Error: Dynamic Symbol Retrieval Error: Win32 error 127
    at DynamicLibrary.get (c:\Trabajo\Mesh01\wear-test-track0\node_modules\argon2-ffi\node_modules\ffi\lib\dynamic_library.js:112:11)
    at c:\Trabajo\Mesh01\wear-test-track0\node_modules\argon2-ffi\node_modules\ffi\lib\library.js:50:19
    at Array.forEach (native)
    at new Library (c:\Trabajo\Mesh01\wear-test-track0\node_modules\argon2-ffi\node_modules\ffi\lib\library.js:47:28)
    at Object.<anonymous> (c:\Trabajo\Mesh01\wear-test-track0\node_modules\argon2-ffi\lib\library.js:23:11)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

```

The error is triggered when doing:  

`var argon2i = require('argon2-ffi').argon2i;`

 These are the npm install notes:  

```
> ref@1.3.2 install c:\Trabajo\Mesh01\wear-test-track0\node_modules\argon2-ffi\node_modules\ref
> node-gyp rebuild


c:\Trabajo\Mesh01\wear-test-track0\node_modules\argon2-ffi\node_modules\ref>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  binding.cc
  win_delay_load_hook.c
     Creating library c:\Trabajo\Mesh01\wear-test-track0\node_modules\argon2-ffi\node_modules\ref\build\Release\binding.
  lib and object c:\Trabajo\Mesh01\wear-test-track0\node_modules\argon2-ffi\node_modules\ref\build\Release\binding.exp
  Generating code
  Finished generating code
  binding.vcxproj -> c:\Trabajo\Mesh01\wear-test-track0\node_modules\argon2-ffi\node_modules\ref\build\Release\\binding.
  node

> ffi@2.0.0 install c:\Trabajo\Mesh01\wear-test-track0\node_modules\argon2-ffi\node_modules\ffi
> node-gyp rebuild


c:\Trabajo\Mesh01\wear-test-track0\node_modules\argon2-ffi\node_modules\ffi>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Building assembly file ..\..\..\deps\libffi\src\x86\win64.asm
   Assembling: ..\..\..\deps\libffi\src\x86\win64.asm
  prep_cif.c
  types.c
  raw_api.c
  java_raw_api.c
  closures.c
  ffi.c
  win_delay_load_hook.c
  ffi.vcxproj -> c:\Trabajo\Mesh01\wear-test-track0\node_modules\argon2-ffi\node_modules\ffi\build\Release\\libffi.lib
  ffi.cc
  callback_info.cc
  threaded_callback_invokation.cc
  win32-dlfcn.cc
  win_delay_load_hook.c
     Creating library c:\Trabajo\Mesh01\wear-test-track0\node_modules\argon2-ffi\node_modules\ffi\build\Release\ffi_bind
  ings.lib and object c:\Trabajo\Mesh01\wear-test-track0\node_modules\argon2-ffi\node_modules\ffi\build\Release\ffi_bind
  ings.exp
  Generating code
  Finished generating code
  ffi_bindings.vcxproj -> c:\Trabajo\Mesh01\wear-test-track0\node_modules\argon2-ffi\node_modules\ffi\build\Release\\ffi
  _bindings.node

> argon2-ffi@1.0.0 install c:\Trabajo\Mesh01\wear-test-track0\node_modules\argon2-ffi
> node-gyp rebuild


c:\Trabajo\Mesh01\wear-test-track0\node_modules\argon2-ffi>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  argon2.c
  core.c
  blake2b.c
  thread.c
..\libargon2\src\argon2.c(221): warning C4267: '=': conversion from 'size_t' to 'uint32_t', possible loss of data [c:\Tr
abajo\Mesh01\wear-test-track0\node_modules\argon2-ffi\build\argon2.vcxproj]
  encoding.c
  opt.c
  win_delay_load_hook.c
  Generating code
  Finished generating code
  argon2.vcxproj -> c:\Trabajo\Mesh01\wear-test-track0\node_modules\argon2-ffi\build\Release\\argon2.dll
```

I'm using Windows 10 on a 64 bits i7 processor.

Thank you.

**Comment by cjlarose** [comment] 2016-06-27 01:13
Sorry about this! What version of Node.js are you using?

**Comment by Urik** [comment] 2016-07-01 14:22
Don't worry! v4.4.4  
Thanks for looking into it.

**Comment by Slayther** [comment] 2016-07-02 08:26
I'm getting the same error with same-ish trace.
Full output:

```
C:\Users\Raketa\Desktop\node-app>npm start

> website-using-express@0.0.1 start C:\Users\Raketa\Desktop\node-app
> node server.js

C:\Users\Raketa\Desktop\node-app\node_modules\ffi\lib\dynamic_library.js:112
    throw new Error('Dynamic Symbol Retrieval Error: ' + this.error())
    ^

Error: Dynamic Symbol Retrieval Error: Win32 error 127
    at DynamicLibrary.get (C:\Users\Raketa\Desktop\node-app\node_modules\ffi\lib\dynamic_library.js:112:11)
    at C:\Users\Raketa\Desktop\node-app\node_modules\ffi\lib\library.js:50:19
    at Array.forEach (native)
    at new Library (C:\Users\Raketa\Desktop\node-app\node_modules\ffi\lib\library.js:47:28)
    at Object.<anonymous> (C:\Users\Raketa\Desktop\node-app\node_modules\argon2-ffi\lib\library.js:23:11)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! website-using-express@0.0.1 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the website-using-express@0.0.1 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the website-using-express package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs website-using-express
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls website-using-express
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Raketa\Desktop\node-app\npm-debug.log
```

**Comment by PlasmaPower** [comment] 2016-07-02 12:55
Since someone else got this error, it looks like it's more than just bad luck/configuration unfortunately. Here's my troubleshooting:

Googling "win32 error 127" gives a lot more results than "'Dynamic Symbol Retrieval Error". The error is ERROR_PROC_NOT_FOUND, "The specified procedure could not be found.". 

It looks like the problem can stem from several things:
- The more obvious case of the library not having the procedure (function) used by Node. This is the likely cause, as the error occurs [when loading a specific function](https://github.com/node-ffi/node-ffi/blob/master/lib/dynamic_library.js#L108). However, I don't see why the dll would be missing a function. If you have visual studio installed, could you do `dumpbin /EXPORTS path/to/argon2.dll`? That should list exported functions, we can see if they match up with what we're using.
- You have multiple DLLs with different versions in the library loading path. From my understanding of node-argon2, it will specify a static path to load from, which would mean that this couldn't happen.
- Argon2 has it's own runtime dependency which it is failing to load. However, I know that this is not the case.

So, the first case seems like the only likely one. If you could get the functions exported from the dll that would be great.

**Comment by Slayther** [comment] 2016-07-02 13:02
I would love to help, but I'm not sure where or how I should run that command?

**Comment by Urik** [comment] 2016-07-02 13:05
Here's mine, sorry if something's missing, I'm on a rush.

```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin>dumpbin /EXPORTS "C:\Trabajo\Mesh01\wear-test-track0\node_modules\argon2-ffi\build\Release\argon2.dll"
Microsoft (R) COFF/PE Dumper Version 14.00.23303.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file C:\Trabajo\Mesh01\wear-test-track0\node_modules\argon2-ffi\build\Release\argon2.dll

File Type: DLL

  Summary

        2000 .data
        1000 .pdata
        9000 .rdata
        1000 .reloc
        1000 .rsrc
        A000 .text
```

**Comment by Slayther** [comment] 2016-07-02 13:06
I figured it out. Here is mine:

```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin>dumpbin /EXPORTS C:\Users\Raketa\Desktop\node-app\node_modules\argon2-ffi\build\Release\argon2.dll
Microsoft (R) COFF/PE Dumper Version 14.00.23506.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file C:\Users\Raketa\Desktop\node-app\node_modules\argon2-ffi\build\Release\argon2.dll

File Type: DLL

  Summary

        2000 .data
        1000 .gfids
        1000 .pdata
        9000 .rdata
        1000 .reloc
        1000 .rsrc
        A000 .text

C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin>
```

**Comment by PlasmaPower** [comment] 2016-07-02 14:23
That's odd, it would appear that the library is being built wrong as it exports no functions. Normally you'd see an output something like the one in [this StackOverflow post](http://stackoverflow.com/a/6634722/3352674).

**Comment by PlasmaPower** [comment] 2016-07-02 14:32
Can you try building argon2 manually, and replacing the built DLL with the manually built one? I'd like to confirm that this is the problem. I'm not sure what is causing it yet.

**Comment by Slayther** [comment] 2016-07-03 09:50
I tried building with instructions from [the repository](https://github.com/cjlarose/argon2-ffi#contributing), and replaced the dll file, but the same error appears. I'm not sure if I have built it correctly, or should I have used something different..

Here is the output:

```
C:\Users\Raketa\Desktop\argon2-ffi>git submodule init

C:\Users\Raketa\Desktop\argon2-ffi>git submodule update

C:\Users\Raketa\Desktop\argon2-ffi>node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.2.0 | win32 | x64
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'C:\\Users\\Raketa\\AppData\\Roaming\\nvm\\v6.2.0\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Raketa\\Desktop\\argon2-ffi\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Raketa\\AppData\\Roaming\\nvm\\v6.2.0\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Raketa\\.node-gyp\\6.2.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Raketa\\.node-gyp\\6.2.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Raketa\\AppData\\Roaming\\nvm\\v6.2.0\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\Raketa\\Desktop\\argon2-ffi',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\Raketa\\Desktop\\argon2-ffi\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  argon2.c
  core.c
..\libargon2\src\argon2.c(215): warning C4267: '=': conversion from 'size_t' to 'uint32_t', possible loss of data [C:\U
sers\Raketa\Desktop\argon2-ffi\build\argon2.vcxproj]
  blake2b.c
  thread.c
  encoding.c
  opt.c
  win_delay_load_hook.cc
  Generating code
  Finished generating code
  argon2.vcxproj -> C:\Users\Raketa\Desktop\argon2-ffi\build\Release\\argon2.dll
gyp info ok

C:\Users\Raketa\Desktop\argon2-ffi>npm run build

> argon2-ffi@1.0.0 build C:\Users\Raketa\Desktop\argon2-ffi
> babel src -d lib

src\index.js -> lib\index.js
src\library.js -> lib\library.js
```

**Comment by PlasmaPower** [comment] 2016-07-03 11:58
@Slayther That's how you would build it through argon2-fii, I should have been a bit more specific. Try building argon2 standalone (without Node or argon2-ffi). It can be found here: https://github.com/P-H-C/phc-winner-argon2 and I think it can be built with visual studio.

Once you have built the DLL, replace the DLL in `argon2-fii/build/Release` with the DLL you built.

**Comment by Slayther** [comment] 2016-07-03 17:51
Excuse my ignorance, but I am not sure how to build it. I tried running make with command prompt at the folder cloned from git.

```
C:\Users\Raketa\Desktop\argon2>make
      0 [main] us 0 init_cheap: VirtualAlloc pointer is null, Win32 error 487
AllocationBase 0x684B0000, BaseAddress 0x68540000, RegionSize 0x2000, State 0x1000
C:\MinGW\bin\make.exe: *** Couldn't reserve space for cygwin's heap, Win32 error 0

C:\Users\Raketa\Desktop\argon2>make run
make: *** No rule to make target `run'.  Stop.

C:\Users\Raketa\Desktop\argon2>make install
make: *** No rule to make target `install'.  Stop.

C:\Users\Raketa\Desktop\argon2>make build
make: *** No rule to make target `build'.  Stop.

C:\Users\Raketa\Desktop\argon2>make --version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i686-pc-msys
```

**Comment by PlasmaPower** [comment] 2016-07-03 18:13
@Slayther Assuming your Node isn't built through Cygwin, don't build argon2 through Cygwin. Try opening the project in Visual Studio (try the vs2015 folder and subfolders, and if that fails, simply import the sources).

**Comment by Slayther** [comment] 2016-07-03 19:08
I opened one of `.vcxproj` files in VS and pressed `Build > Build Solution`. There were no errors, but there is no `.dll`. What else should I do to get it?

**Comment by PlasmaPower** [comment] 2016-07-03 19:17
@Slayther Did you open the `Argon2Opt` one? A bit of research shows that should produce a build similar to what we're doing. If that doesn't give you a DLL, try creating a new console project with application type DLL, copying in the c files specified [here](https://github.com/cjlarose/argon2-ffi/blob/master/binding.gyp), copying in all header files (.h), and building.

**Comment by Slayther** [comment] 2016-07-03 19:21
Yes, I opened `Argon2Opt.vcxproj`.

Are there any additional options I should check?

**Comment by PlasmaPower** [comment] 2016-07-03 19:23
@Slayther What's the build log? If it's long, post it at https://gist.github.com/

**Comment by PlasmaPower** [comment] 2016-07-03 19:24
@Slayther Also, make sure the application type is set to DLL in the project options.

**Comment by Slayther** [comment] 2016-07-03 19:28
Here is the [gist](https://gist.github.com/Slayther/c90af876ba930e283bc87bfcd6da0e1b)

Project options of the application cloned from git or the one I would create manually and import the code files into?

**Comment by PlasmaPower** [comment] 2016-07-03 19:29
@Slayther The one cloned for git (well both really) - it should be preset to DLL but it looks like it isn't for some reason (it's building an EXE).

**Comment by Slayther** [comment] 2016-07-03 19:31
I'm not sure how I can switch the type to dll, can't find the option. Unless I create it manually like you said.

**Comment by PlasmaPower** [comment] 2016-07-03 19:35
@Slayther Maybe it's in output type? I'll be rebooting into windows in a while anyway, so I'll see if I can't look into this while I'm there. Basically look for a dropdown that has a DLL selection (probably labeled as a type).

**Comment by Slayther** [comment] 2016-07-03 19:40
Going to `Project > Properties` has no options that say dll or anything similar. Not sure where I would find the option.

**Comment by PlasmaPower** [comment] 2016-07-03 19:41
@Slayther Okay, it should be there. I'm rebooting into Windows to investigate.

**Comment by PlasmaPower** [comment] 2016-07-03 20:18
I forgot what a pain it is to setup a proper Windows dev environment...

**Comment by Slayther** [comment] 2016-07-03 20:21
Can I do anything further?

**Comment by PlasmaPower** [comment] 2016-07-03 20:42
@Slayther I figured it out; Properties -> General -> Project Defaults - set to Dynamic Library (.dll), then a bit up there's a Target Extension, change that to .dll instead of .exe. I'm seeing if I can run it with that dll now.

**Comment by PlasmaPower** [comment] 2016-07-03 20:43
Because I can't get my node-gyp environment setup properly (I think I need VS2013, I have VS2015 for argon2) I can't test the built DLL.

**Comment by Slayther** [comment] 2016-07-03 20:44
Ok, I will try it out

**Comment by PlasmaPower** [comment] 2016-07-03 20:48
Odd, I don't see any exports in my VS built DLL.

**Comment by Slayther** [comment] 2016-07-03 20:48
Where is that `Properties`? There is no `General` under `Project > Properties`

**Comment by PlasmaPower** [comment] 2016-07-03 20:48
@Slayther Right click Argon2Opt on the right

**Comment by Slayther** [comment] 2016-07-03 20:49
I just choose dll and build?

**Comment by PlasmaPower** [comment] 2016-07-03 20:50
@Slayther You choose DLL in two spots, then build yes.

**Comment by Slayther** [comment] 2016-07-03 20:51
In 2 spots?
There is another under General > General, but it's dll already. Is that the one?

**Comment by Slayther** [comment] 2016-07-03 20:51
There is another under General, but it's dll already. Is that the one?

**Comment by PlasmaPower** [comment] 2016-07-03 20:52
@Slayther Both general and general -> project defaults -> configuration type.

**Comment by Slayther** [comment] 2016-07-03 20:52
Ok, then I'm good. Building

**Comment by Slayther** [comment] 2016-07-03 20:54
Okay, now there are multiple .dlls, for each folder. How do I get the single one I need?

**Comment by PlasmaPower** [comment] 2016-07-03 20:54
This just got significantly more complicated. It looks like the problem is that for VS you have to put __declspec(dllexport) before any function you want to export when building a DLL. That's why our built DLLs have no functions.

**Comment by PlasmaPower** [comment] 2016-07-03 20:54
@Slayther should be the Argon2Opt one

**Comment by PlasmaPower** [comment] 2016-07-03 20:55
There's no way to automatically export all functions (that's built into VS at least), so it looks like it won't easily work unless argon2 adds specific support for Visual Studio.

**Comment by Slayther** [comment] 2016-07-03 20:56
Yup, still getting the same error.

**Comment by Slayther** [comment] 2016-07-03 20:57
Wish I had more knowledge regarding all this. I would love to help with that.

**Comment by Slayther** [comment] 2016-07-03 21:01
Re-running dumpbin gives different output now, if that helps

```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin>dumpbin /EXPORTS C:\Users\Raketa\Desktop\node-app\node_modules\argon2-ffi\build\Release\argon2.dll
Microsoft (R) COFF/PE Dumper Version 14.00.23506.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file C:\Users\Raketa\Desktop\node-app\node_modules\argon2-ffi\build\Release\argon2.dll

File Type: DLL

  Summary

        1000 .00cfg
        1000 .data
        1000 .gfids
        1000 .idata
        3000 .pdata
        6000 .rdata
        1000 .reloc
        1000 .rsrc
       1A000 .text
       10000 .textbss
```

**Comment by PlasmaPower** [comment] 2016-07-03 21:04
I figured it out! In argon2.h, change:

``` c++
#ifdef A2_VISCTL
#define ARGON2_PUBLIC __attribute__((visibility("default")))
#else
#define ARGON2_PUBLIC
#endif
```

to:

``` c++
#ifdef A2_VISCTL
#define ARGON2_PUBLIC __attribute__((visibility("default")))
#elif _MSC_VER
#define ARGON2_PUBLIC __declspec(dllexport)
#else
#define ARGON2_PUBLIC
#endif
```

Then the built DLL has the correct `dumpbin /exports` output! I think that should work!

**Comment by PlasmaPower** [comment] 2016-07-03 21:07
Fixed with P-H-C/phc-winner-argon2#147

**Comment by Slayther** [comment] 2016-07-03 21:09
Yes, it does not throw any errors on include!

**Comment by Slayther** [comment] 2016-07-03 21:11
Will test my app now

**Comment by PlasmaPower** [comment] 2016-07-03 21:11
I think we can close this issue when the linked PR for argon2 gets merged. Until then, @Urik you can manually build the DLL in visual studio as described above.

**Comment by Slayther** [comment] 2016-07-03 21:14
Well, I have a bug in it and it hangs.. Oh well, no errors, nice work!

**Comment by Slayther** [comment] 2016-07-03 21:21
How long should this execute for?
`argon.argon2i.hash("123456", 10, function (err, hash) {console.log(hash);});`

Edit:
It just seems to hang forever.

Edit:
It seems like it's not doing much as Task Manager shows 0% for CPU usage..

**Comment by PlasmaPower** [comment] 2016-07-03 21:44
@Slayther I think you missed the move to promises. A breaking update switched the style from callbacks to promises. Try this:

``` js
argon.argon2i.hash("123456", 10).then(console.log).catch(console.error);
```

**Comment by PlasmaPower** [comment] 2016-07-03 21:47
That'll throw an error BTW, you're probably looking for this:

``` js
argon.argon2i.hash("123456", new Buffer(10)).then(console.log).catch(console.error);
```

**Comment by Slayther** [comment] 2016-07-03 23:02
Ahh, thank you very much!

**Closed as completed** 2016-07-06 16:41 UTC
