### ISSUE TITLE
ENOENT: no such file or directory, open node_modules/argon2-ffi/build/Release/argon2.so

### ISSUE THREAD

**Issue by noo-zh** [cjlarose/argon2-ffi#28] opened 2018-10-31 12:56 UTC
**Stack:**
Ubuntu 18.04.1 LTS
NODE v8.10.0
NPM 3.5.2

**Bug??**
My app returns error: `ENOENT: no such file or directory, open node_modules/argon2-ffi/build/Release/argon2.so`. The problem is, that `argon2.so` has been built to `node_modules/argon2-ffi/build/Release/lib.target` and `argon2-ffi/build/Release/obj.target`, not sure why. When I copy the file to parent folder, everything works as expected.

**Comment by cjlarose** [comment] 2018-12-19 19:31
Thanks for looking into this issue @icarus-sullivan! Do you have an idea about the circumstances that cause `argon2.so` to be built into that `lib.target` directory? I'd love to be able to reproduce this problem so I can make sure future updates to this project don't break.

I wrote a Dockerfile that shows that under Node 8 on Ubuntu 18.04, that it is at least possible for the generated `.so` file to end up at `node_modules/argon2-ffi/build/Release/argon2.so` (it actually also builds it at `node_modules/argon2-ffi/build/Release/obj.target/argon2.so`

```dockerfile
FROM ubuntu:18.04

RUN apt-get update && apt-get install -y curl gnupg
RUN curl --silent --location https://deb.nodesource.com/setup_8.x | bash
RUN apt-get update && apt-get install -y \
  nodejs \
  build-essential \
  git \
  coreutils \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /root
RUN echo '{"dependencies": {"argon2-ffi":"cjlarose/argon2-ffi#968d373bbf04db46748cb1c87033f61971c1d047"}}' > package.json
RUN npm install
RUN find . -name '*.so' | xargs sha256sum
```

```
Step 8/8 : RUN find . -name '*.so' | xargs sha256sum
 ---> Running in ab3104e86aa7
09d66fabfbbedba25a3cf9e24bf01622b433f636028c1c71549be4207a9e36f5  ./node_modules/argon2-ffi/build/Release/argon2.so
09d66fabfbbedba25a3cf9e24bf01622b433f636028c1c71549be4207a9e36f5  ./node_modules/argon2-ffi/build/Release/obj.target/argon2.so
```

Do you know a way I can reproduce the problem?

**Comment by icarus-sullivan** [comment] 2018-12-19 21:54
@cjlarose No problem, really like your library here and want to use it in some open source work I'm doing. When I get home I'll include the following information that might help. 

- build output
- node version
- npm version
- (ubuntu) linux version

Also, sorry for all the spam with MR's and such, took me a while to find the correct fix that supported legacy paths as well as `lib.target` paths and also not interfere with pre-built binaries. 

I do know I was building in the latest Ubuntu LTS with version `7.3.0` of gcc. Yet, another thought I had was that maybe my `solution` would be better done in the makefile, or if there is an error it is possibly located in the makefile itself when building the binaries.

**Comment by icarus-sullivan** [comment] 2018-12-20 03:03
I found the issue. 

**Global node-gyp**
`node-gyp rebuild`
```
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.10.0 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/share/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/sully/Desktop/argon2-ffi/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/share/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/include/nodejs/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/usr/include/nodejs',
gyp info spawn args   '-Dnode_gyp_dir=/usr/share/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/usr/include/nodejs/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/sully/Desktop/argon2-ffi',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/sully/Desktop/argon2-ffi/build'
  CC(target) Release/obj.target/argon2/libargon2/src/argon2.o
  CC(target) Release/obj.target/argon2/libargon2/src/core.o
  CC(target) Release/obj.target/argon2/libargon2/src/blake2/blake2b.o
  CC(target) Release/obj.target/argon2/libargon2/src/thread.o
  CC(target) Release/obj.target/argon2/libargon2/src/encoding.o
  CC(target) Release/obj.target/argon2/libargon2/src/opt.o
  SOLINK(target) Release/obj.target/argon2.so
  COPY Release/lib.target/argon2.so
make: Leaving directory '/home/sully/Desktop/argon2-ffi/build'
gyp info ok
```

**node_modules node-gyp**
`node ./node_modules/node-gyp/bin/node-gyp.js rebuild`
```
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@8.10.0 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/home/sully/Desktop/argon2-ffi/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/sully/Desktop/argon2-ffi/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/sully/Desktop/argon2-ffi/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/sully/.node-gyp/8.10.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/sully/.node-gyp/8.10.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/sully/Desktop/argon2-ffi/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/sully/.node-gyp/8.10.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/sully/Desktop/argon2-ffi',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/sully/Desktop/argon2-ffi/build'
  CC(target) Release/obj.target/argon2/libargon2/src/argon2.o
  CC(target) Release/obj.target/argon2/libargon2/src/core.o
  CC(target) Release/obj.target/argon2/libargon2/src/blake2/blake2b.o
  CC(target) Release/obj.target/argon2/libargon2/src/thread.o
  CC(target) Release/obj.target/argon2/libargon2/src/encoding.o
  CC(target) Release/obj.target/argon2/libargon2/src/opt.o
  SOLINK(target) Release/obj.target/argon2.so
  COPY Release/argon2.so
make: Leaving directory '/home/sully/Desktop/argon2-ffi/build'
gyp info ok
```

Notice the final `COPY` line of node-gyp. It seems like something has changed in the way it compiles and copies over libs. Code migration is a common issue in javascript, it should have been something I thought of right away. 

**Resolution**
So now the question, what do we do? 

1. We can say that this is not an argon2-ffi issue, but one with node-gyp compatibility and @cjlarose can close the issue. 
2. We can remediate the node-gyp issue and add a file check in the library. 
    a. include node-gyp version checks in travisCI
    b. include some form of build artifact checking for the rogue argon2.so 
3. Bump the version of node-gyp to 3.8.0 to avoid weird binary outputs, and notify clients they need at least that version for local builds. 

The biggest pro to the change would be to allow for numerous node-gyp versions from ^3.3.1 on to work. 
The biggest con is that having to change code based on a dependency is that it may change again in the future. 

In either case, my [MR](https://github.com/cjlarose/argon2-ffi/pull/31) should be modified somewhat to reflect the actual output check, with better-suited variable names.

**Comment by cjlarose** [comment] 2018-12-21 16:06
I'm not sure that the `node-gyp` version alone explains the differences in where the compiled `.so` files ends up.

This Dockerfile produces an image with `node-gyp@3.6.2` is installed globally.

```Dockerfile
FROM ubuntu:18.04

RUN apt-get update && apt-get install -y curl gnupg
RUN curl --silent --location https://deb.nodesource.com/setup_8.x | bash
RUN apt-get update && apt-get install -y \
  nodejs \
  build-essential \
  git \
  coreutils \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /root
RUN echo '{"dependencies": {"argon2-ffi":"cjlarose/argon2-ffi#968d373bbf04db46748cb1c87033f61971c1d047"}}' > package.json
RUN npm install
RUN npm install -g node-gyp@3.6.2
```

If I run a container with that image, I can run `node-gyp` rebuild, but it writes the `.so` file to `build/Release/obj.target/argon2.so`

```
root@e00511d00ed1:~# cd node_modules/argon2-ffi/
root@e00511d00ed1:~/node_modules/argon2-ffi# rm -rf build/
root@e00511d00ed1:~/node_modules/argon2-ffi# node-gyp --version
v3.6.2
root@e00511d00ed1:~/node_modules/argon2-ffi# node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.14.0 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/root/node_modules/argon2-ffi/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/8.14.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/8.14.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/8.14.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/root/node_modules/argon2-ffi',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/root/node_modules/argon2-ffi/build'
  CC(target) Release/obj.target/argon2/libargon2/src/argon2.o
  CC(target) Release/obj.target/argon2/libargon2/src/core.o
  CC(target) Release/obj.target/argon2/libargon2/src/blake2/blake2b.o
  CC(target) Release/obj.target/argon2/libargon2/src/thread.o
  CC(target) Release/obj.target/argon2/libargon2/src/encoding.o
  CC(target) Release/obj.target/argon2/libargon2/src/opt.o
  SOLINK(target) Release/obj.target/argon2.so
  COPY Release/argon2.so
make: Leaving directory '/root/node_modules/argon2-ffi/build'
gyp info ok
```

**Comment by cjlarose** [comment] 2018-12-21 16:09
It would be nice if there was a way to specify to `node-gyp` where to write the `.so` file explicitly. 

Alternatively, maybe it makes more sense just to change

https://github.com/cjlarose/argon2-ffi/blob/968d373bbf04db46748cb1c87033f61971c1d047/src/library.js#L5

to read from `path.join(__dirname, '..', 'build', 'Release', 'obj.target', 'argon2');` instead, since I think in both of your cases, the `.so` file is present in that directory (before it is copied somewhere else).

**Comment by icarus-sullivan** [comment] 2018-12-22 18:39
@cjlarose I think this is the best option as well. I updated the pull request to reflect that and tested locally, everything looked good. I tried to create a branch to squash all commits but I don't have access which is fine. If you decide to use my patch I believe there is a `squash and merge` feature for repo managers to use.

**Comment by cjlarose** [comment] 2018-12-28 00:26
Changes look great. I'll merge and publish a new version to `npm`.

**Closed as completed** 2018-12-28 00:25 UTC

**Comment by cjlarose** [comment] 2018-12-28 00:37
argon2-ffi@1.1.1 is now published to npm with the fix for this issue.
